### ISSUE TITLE
Unable to Climb Ladders

### ISSUE THREAD

**Issue by tborton-code** [rc-nunez-gonzalez/PinkExpansion#2] opened 2022-06-30 23:32 UTC
I have been putting together a custom modpack and I had 91 mods installed including this one. When I loaded into a single-player world to test things, I found I couldn't climb ladders. I went through an extensive process of testing various combinations of mods, and in the end I can only conclude that the compatibility is with this mod and one of the others. 
I can attach my mod list below if you need it, and it may be of use to you to know that I was running 1.18.2, Forge 40.1.53.
I hope this is something you may be able to solve, as I love the work you've put in on this mod!

**Comment by rc-nunez-gonzalez** [comment] 2022-07-01 00:59
Ok, let me check the issue maybe it could be a problem with datapacks, let me see I'll fix this as soon as possible

**Comment by tborton-code** [comment] 2022-07-01 03:31
No rush, but thank you! Do you need me to provide you with anything?

**Comment by rc-nunez-gonzalez** [comment] 2022-07-01 03:58
Don't worry, the issue is now fixed, you can download the fixed version [HERE](https://www.curseforge.com/minecraft/mc-mods/pink-expansion/files/3854921), thanks for reporting and please if you find any more bugs tell me so I can fix them

**Closed as completed** 2022-07-01 04:01 UTC
